import hre from "hardhat";
import * as fs from "fs";
import * as path from "path";
import { keccak256, toHex } from "viem";

const DEPLOYMENTS_JSON = path.resolve(__dirname, "../../../deployments.json");
const DEPLOYMENTS_TS = path.resolve(
	__dirname,
	"../../../web/src/config/deployments.ts"
);

// ── Protocol Commons AttestationRegistry v1 on Paseo ─────────────────────────
const ATTESTATION_REGISTRY_PASEO = "0x4d018c530e01bbc98b042a18a4d4090658bcd8f3";

// Nullifier seed — must match what frontend uses
const NULLIFIER_SEED = 123456789n;

// Poseidon hash of UIDAI signing public key — from circuit public signals [0]
const PUBKEY_HASH = BigInt(
	"7159552241047614681013946344274430157054820687880791674287250194862110506098"
);

// Schema — keccak256 of schema string (v1 uses free-form bytes32)
const SCHEMA_STRING = "zk.pan.indian.national.v1";
const SCHEMA = keccak256(toHex(SCHEMA_STRING));

const paseoAssetHub = {
	id: 420420417,
	name: "Paseo Asset Hub",
	nativeCurrency: { name: "PAS", symbol: "PAS", decimals: 18 },
	rpcUrls: {
		default: { http: ["https://testnet-passet-hub-eth-rpc.polkadot.io"] },
		public: { http: ["https://testnet-passet-hub-eth-rpc.polkadot.io"] },
	},
} as const;

// ── Deployment helpers ────────────────────────────────────────────────────────

function updateDeployments(addresses: {
	verifier: string;
	anonDigiLocker: string;
	panAttester: string;
	attestationRegistry: string;
	schema: string;
}) {
	let data: Record<string, string | null> = {
		evm: null,
		pvm: null,
		verifier: null,
		anonDigiLocker: null,
		panAttester: null,
		attestationRegistry: null,
		schema: null,
	};

	try {
		data = JSON.parse(fs.readFileSync(DEPLOYMENTS_JSON, "utf-8"));
	} catch {
		// File doesn't exist yet
	}

	data.verifier = addresses.verifier;
	data.anonDigiLocker = addresses.anonDigiLocker;
	data.panAttester = addresses.panAttester;
	data.attestationRegistry = addresses.attestationRegistry;
	data.schema = addresses.schema;

	fs.writeFileSync(DEPLOYMENTS_JSON, JSON.stringify(data, null, 2) + "\n");

	const fmt = (v: string | null) => (v === null ? "null" : `"${v}"`);
	const ts = `// Auto-generated by contract deploy scripts — do not edit manually
export const deployments: {
\tevm: string | null;
\tpvm: string | null;
\tverifier: string | null;
\tanonDigiLocker: string | null;
\tpanAttester: string | null;
\tattestationRegistry: string | null;
\tschema: string | null;
} = {
\tevm: ${fmt(data.evm)},
\tpvm: ${fmt(data.pvm)},
\tverifier: ${fmt(data.verifier)},
\tanonDigiLocker: ${fmt(data.anonDigiLocker)},
\tpanAttester: ${fmt(data.panAttester)},
\tattestationRegistry: ${fmt(data.attestationRegistry)},
\tschema: ${fmt(data.schema)},
};
`;
	try {
		fs.writeFileSync(DEPLOYMENTS_TS, ts);
	} catch {
		// web/src/config/deployments.ts may not exist in all setups
	}
}

async function deploySimple(
	walletClient: Awaited<ReturnType<typeof hre.viem.getWalletClients>>[0],
	publicClient: Awaited<ReturnType<typeof hre.viem.getPublicClient>>,
	contractName: string,
	args: unknown[] = []
): Promise<string> {
	const artifact = await hre.artifacts.readArtifact(contractName);

	const hash = await walletClient.deployContract({
		abi: artifact.abi,
		bytecode: artifact.bytecode as `0x${string}`,
		args,
	});

	const receipt = await publicClient.waitForTransactionReceipt({
		hash,
		timeout: 120_000,
	});

	if (!receipt.contractAddress) {
		throw new Error(`Deploy tx ${hash} did not create a contract`);
	}

	return receipt.contractAddress;
}

// ── Main ──────────────────────────────────────────────────────────────────────

async function main() {
	const [walletClient] = await hre.viem.getWalletClients({
		chain: paseoAssetHub,
	});
	const publicClient = await hre.viem.getPublicClient({
		chain: paseoAssetHub,
	});

	console.log("════════════════════════════════════════════════");
	console.log("  ZK PAN Verifier — Deployment");
	console.log("════════════════════════════════════════════════");
	console.log("Deployer:  ", walletClient.account.address);
	console.log("Registry:  ", ATTESTATION_REGISTRY_PASEO);
	console.log("Schema:    ", SCHEMA, `(${SCHEMA_STRING})`);
	console.log("");

	// 1. Deploy Groth16 Verifier
	console.log("[1/3] Deploying Verifier...");
	const verifier = await deploySimple(walletClient, publicClient, "Verifier");
	console.log("      ✅ Verifier:", verifier);

	// 2. Deploy AnonDigiLocker
	console.log("[2/3] Deploying AnonDigiLocker...");
	const anonDigiLocker = await deploySimple(
		walletClient,
		publicClient,
		"AnonDigiLocker",
		[verifier, PUBKEY_HASH]
	);
	console.log("      ✅ AnonDigiLocker:", anonDigiLocker);

	// 3. Deploy PANAttester
	console.log("[3/3] Deploying PANAttester...");
	const panAttester = await deploySimple(
		walletClient,
		publicClient,
		"PANAttester",
		[anonDigiLocker, ATTESTATION_REGISTRY_PASEO, NULLIFIER_SEED]
	);
	console.log("      ✅ PANAttester:", panAttester);

	// Update deployments
	updateDeployments({
		verifier,
		anonDigiLocker,
		panAttester,
		attestationRegistry: ATTESTATION_REGISTRY_PASEO,
		schema: SCHEMA,
	});

	console.log("\nUpdated deployments.json");

	console.log("\n════════════════════════════════════════════════");
	console.log("  DEPLOYMENT COMPLETE");
	console.log("════════════════════════════════════════════════");
	console.log("Verifier:            ", verifier);
	console.log("AnonDigiLocker:      ", anonDigiLocker);
	console.log("PANAttester:         ", panAttester);
	console.log("AttestationRegistry: ", ATTESTATION_REGISTRY_PASEO);
	console.log("Schema:              ", SCHEMA);
	console.log("════════════════════════════════════════════════");
}

main().catch((error) => {
	console.error(error);
	process.exitCode = 1;
});